### ISSUE TITLE
Extension razorpay is either disabled or the path is not existed

### ISSUE THREAD

**Issue by dheeth** [coder-palak/evershop-razorpay#1]
I am using latest version of evershop and not able to use the extension with the readme provided

**Comment by dheeth** [comment]
Changed `"resolve": "node_modules/evershop-razorpay/razorpay",` to `"resolve": "node_modules/evershop-razorpay",`

and run `npm run build` again which resolved the issue

**Comment by dhileep47** [comment]
Any code changes required in the frontstore or did the package work out of the box?
 when i click place order button from the checkout nothing will happen. Kindly reply with the proper integration steps
